### ISSUE TITLE
TODO Features Stuff

### ISSUE THREAD

**Issue by hueyyeng** [hueyyeng/Nande#1]
- [x] Flip/Flop to match... RV? Or maybe just use flip horizontal/vertical wording
- [x] Rotate 90/180 clockwise/counter clockwise
- [x] Proper arbitrary zoom level (right now it is broken except for Actual Size and Fit Image to View)
- [ ] Expose a floating info "tooltip" when user right click on the viewer (or maybe just copy wholesale from Nuke viewer info/status bar)
- [ ] Investigation: Add basic image exposure/manipulation handling and HDR images (least priority for now)

**Comment by hueyyeng** [comment]
Current progress as of 21 March 2024:

- [ ] Working zoom level but need to elegantly handle the zoom rounding percentage but low priority for now...
- [ ] Floating info tooltip QPoint is off by... 3-4 pixels on the Y axis?
- [ ] Create an API for user to save the loaded image as a new file... not sure if want to provide file conversion maybe using Pillow?
